### PR TITLE
update parser

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
This probably shouldn't be merged until #16 has a solution but this can be used for testing. This is an update by a minor version so it shouldn't break anything.

### CODE REVIEW

**Comment by TotallyGamerJet** [comment]
Was this test passing before? It appears to be broken in CC at `(*InitializerList).checkStruct` in `check.go`

**Comment by dennwc** [comment]
It was passing in https://github.com/gotranspile/cxgo/pull/15 at least :thinking:

**Comment by TotallyGamerJet** [comment]
@dennwc It now passes! Now how do you want to go about closing #16? If you tell me what you want the code to look like and generally what files to change I can add that commit too.

**Comment by dennwc** [comment]
Merged, #16 can be solved separately.

**Pull request merged**
