### PR TITLE
Extract headers from go sources to h files

### PR DESCRIPTION
**Pull request by g41797**
Separated include files were created in libs folder:
arpa_inet.h
glob.h
netdb.h
pthread.h
setjmp.h
stdarg.h
stdlib.h
string.h
sys_socket.h
sys_stat.h
sys_time.h
sys_types.h
time.h
unistd.h
wctype.h

Content of every include file above was extracted from corresponding go source file.

Read of includes was implemented via "embed" pkg

### CODE REVIEW

**Review by dennwc — CHANGES_REQUESTED** [review]
Sorry for the late response, I was on vacation.

The approach that you use here looks good, however I know that Go compiler has certain cgo logic that triggers when it finds C files directly in the Go package.

So I think we must move all `.h` files created in this PR to a separate directory. Ideally it should be in `include` as well, but automatic registration will attempt to use them as well. So we either need some blacklist, or add some special logic so that we can file `Header` separately from `Idents` and `Types`.

As a quick solution, we can just move these special headers to `embed` or `custom` directory.

**Comment by g41797** [comment]
We can move these *.h file to **_includes_** directory and move already existing files (created in prev. PR) to new includes/**_embed_** dir
Pros:
- h files under one root
- simple fix 

What do you think?

**Comment by dennwc** [comment]
Sounds good :+1:

**Comment by g41797** [comment]
tomorrow i'll try to fix

**Comment by g41797** [comment]
fixed
how to proceed?

**Comment by dennwc** [comment]
I added a new function `RegisterLibrarySrc` which is used in auto-registration from `include` directory. It is then automatically joined with everything registered via `RegisterLibrary`. So no need for a special `embed` directory. Should work a bit better now :+1:

**Review by dennwc — APPROVED** [review]

**Pull request merged**
